names:
- person
- bicycle
- car
- motorcycle
- airplane
- bus
- train
- truck
- boat
- traffic light
- fire hydrant
- stop sign
- parking meter
- bench
- bird
- cat
- dog
- horse
- sheep
- cow
- elephant
- bear
- zebra
- giraffe
- backpack
- umbrella
- handbag
- tie
- suitcase
- frisbee
- skis
- snowboard
- sports ball
- kite
- baseball bat
- baseball glove
- skateboard
- surfboard
- tennis racket
- bottle
- wine glass
- cup
- fork
- knife
- spoon
- bowl
- banana
- apple
- sandwich
- orange
- broccoli
- carrot
- hot dog
- pizza
- donut
- cake
- chair
- couch
- potted plant
- bed
- dining table
- toilet
- tv
- laptop
- mouse
- remote
- keyboard
- cell phone
- microwave
- oven
- toaster
- sink
- refrigerator
- book
- clock
- vase
- scissors
- teddy bear
- hair drier
- toothbrush
- license plate
nc: 81  # 80 COCO classes + 1 license plate class
train: images/train  # Path to training images
val: images/val      # Path to validation images
test: images/test    # Path to test images

# Add augmentation configurations
augmentation:
  train:
    resize:
      min_size: 640
      max_size: 640
      preserve_aspect_ratio: true
    color:
      brightness_limit: [-0.1, 0.1]
      contrast_limit: [-0.1, 0.1]
      hue_shift_limit: 5
      sat_shift_limit: 10
      val_shift_limit: 10
      p: 0.3
    geometric:
      horizontal_flip: true
      vertical_flip: false
      rotate_limit: 0
      scale_limit: [-0.1, 0.1]
      p: 0.3
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
    bbox_params:
      format: yolo
      min_visibility: 0.3
      min_size: 0.001
      max_aspect_ratio: 20.0
    advanced:
      mosaic_enabled: false  # Disable mosaic augmentation for license plates
      mixup_enabled: false   # Disable mixup augmentation for license plates
      cutout_enabled: false  # Disable cutout augmentation for license plates
    
    # Add size constraints
    size_limits:
      min_box_area: 0.0001  # Minimum box area as fraction of image
      max_box_area: 0.9     # Maximum box area as fraction of image
      min_box_size: 2       # Minimum box dimension in pixels
      max_aspect_ratio: 20.0 # Maximum box aspect ratio

  val:
    resize:
      min_size: 640
      max_size: 640
      preserve_aspect_ratio: true
    normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
    bbox_params:
      format: yolo
      min_visibility: 0.3
      min_size: 0.001

# Add dataset parameters
dataset_params:
  max_objects_per_image: 150
  filter_empty_gt: true
  min_size_threshold: 2
  use_cache: true
  cache_dir: "cache"

# Add training parameters
training:
  batch_size: 16
  num_workers: 4
  pin_memory: true
  shuffle_train: true
  drop_last: true
  max_epochs: 100
  early_stopping_patience: 10